config/routes.rb
Rails.application.routes.draw do
  root to: 'main#home'
  resources :services
  resources :vehicles
  resources :drivers
  resources :routes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :commune
  belongs_to :load
  belongs_to :route, optional: true

  def self.route_and_services_is_a_equal_load(services, load)
    search_service = Service.where(id: services)
    values = search_service.map{|item| item.load_id === load}
    if values.grep_v(true).empty?
      return true
    else
      return false
    end
  end

  def self.assigned_route_to_services(services, route)
    search_service = Service.where(id: services)
    search_service.map { |service| service.update(route: route) }
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  def index
    @services = Service.all.includes(:load)
  end

  def show
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @service }
        format.js
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:type_service, :address, :weight, :commune_id, :route_id, :load_id)
  end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :type_service, 'Tipo de servicio' %>
    <%= form.select(:type_service, [['Buscar encomienda', 'Buscar encomienda'], ['Retirar encomienda', 'Retirar encomienda']], {:prompt => 'Seleccione tipo de servicio...'}, {:class => 'form-control'})%>
  </div>

  <div class="form-group">
    <%= form.label :address, 'Dirección' %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :weight, 'Peso (.Kg)' %>
    <%= form.number_field :weight, class: 'form-control', step: :any %>
  </div>

  <div class="form-group">
    <%= form.label :commune_id, 'Comuna (Solo RM)' %>
    <%= form.collection_select(:commune_id, Commune.all.order(:name), :id, :name, {:prompt => 'Seleccione Comuna...'}, {:class => 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= form.label :load_id, 'Tipo de carga' %>
    <%= form.collection_select(:load_id, Load.all.order(:type_load), :id, :type_load, {:prompt => 'Seleccione tipo de carga...'}, {:class => 'form-control'}) %>
  </div>

  <div class="actions">
    <%= form.submit 'Ordenar servicio', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/destroy.html.erb
<h1>Services#destroy</h1>
<p>Find me in app/views/services/destroy.html.erb</p>

app/views/services/edit.html.erb
<h1>Services#edit</h1>
<p>Find me in app/views/services/edit.html.erb</p>

app/views/services/index.html.erb
<div class="row">
  <div class="col-12">
    <h1>Servicios</h1>
    <p>Listado de todos los servicios (deliveries/pickup)</p>

    <%= link_to 'Agregar Servicio', new_service_path, class: 'btn btn-sm btn-dark mb-2', remote: true %>

    <table class="table" id="services-table">
      <thead class="thead-dark">
      <tr>
        <th scope="col">#id</th>
        <th scope="col">Tipo de servicio</th>
        <th scope="col">Dirección</th>
        <th scope="col">Peso</th>
        <th scope="col">Tipo de carga</th>
        <th scope="col">Ruta</th>
      </tr>
      </thead>
      <tbody>
      <% @services.each do |service| %>
        <tr>
          <th scope="row"><%= service.id %></th>
          <td><%= service.type_service %></td>
          <td><%= service.address %></td>
          <td><%= service.weight %></td>
          <td><%= service.load.type_load %></td>
          <td><%= service.route.present? ? "<span class='service-route'>Ruta: #{service.route.id}</div>".html_safe : "<span class='service-no-route'>Sin Ruta asignada</span>".html_safe %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <%= render "partials/modal" %>
  </div>
</div>

app/views/services/new.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <h1>Services#new</h1>
    <p>Find me in app/views/services/new.html.erb</p>
    <%= render 'form', service: @service %>
  </div>
</div>

app/views/services/new.js.erb
$("#app-modal").modal("show");
$('#modal-title').html("Ingresar nuevo Servicio");
$("#modal-body").html("<%= j render 'form', service: @service %>");

app/views/services/show.html.erb
<div class="row">
  <div class="col-5">
    <%= "Ingreso exitosos para el Servicio #{@service.id}" %>
  </div>
</div>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>