config/routes.rb
Rails.application.routes.draw do
  root to: 'main#home'
  resources :services
  resources :vehicles
  resources :drivers
  resources :routes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_flash_message.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show mt-2" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/partials/_menu_app.html.erb
<div id="navbar-app">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-4 text-left">
        <strong class="logo">RoutesAPP</strong>
      </div>
      <div class="col-8 text-right">
        <%= link_to "Servicios", services_path, class: "btn menu-item" %>
        <%= link_to "Vehiculos", vehicles_path, class: "btn menu-item" %>
        <%= link_to "Conductores", drivers_path, class: "btn menu-item" %>
        <%= link_to "Rutas", routes_path, class: "btn menu-item" %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_modal.html.erb
<div class="modal fade" id="app-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><span id="modal-title"></span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="modal-body" class="modal-body">

      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>