config/routes.rb
Rails.application.routes.draw do
  root to: 'main#home'
  resources :services
  resources :vehicles
  resources :drivers
  resources :routes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :vehicle, optional: true
  has_many :routes, dependent: :destroy

  def full_name
    return "#{name} #{last_name}"
  end

  def self.assign_vehicle_to_driver(driver, vehicle)
    if driver.present? && vehicle.present? && driver.vehicle.nil? && vehicle.driver.nil?
      driver.update(vehicle: vehicle)
      vehicle.update(driver: driver)
     end
  end

end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]
  def index
    @drivers = Driver.all.order(:id).includes(:vehicle)
  end

  def new
    @driver = Driver.new
  end

  def show
  end

  def create
    @driver = Driver.new(driver_params)
    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
        format.js
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
  end

  private

  def set_driver
    @driver = Driver.find(params[:id])
  end

  def driver_params
    params.require(:driver).permit(:name, :last_name, :phone, :email, :vehicle_id)
  end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_driver_tr.html.erb
<% driver = driver.nil? ? @driver : driver %>
<tr id="driver-<%= driver.id %>">
  <th scope="row"><%= driver.id %></th>
  <td><%= driver.name %></td>
  <td><%= driver.last_name %></td>
  <td><%= driver.phone %></td>
  <td><%= driver.email %></td>
  <td><%= driver.vehicle_id ? "id ❱ #{driver.vehicle_id} / #{driver.vehicle.vehicle_patent}" : "Sin vehículo Asignado" %></td>
  <td><%= link_to "editar", edit_driver_path(driver.id), remote: true %></td>
</tr>

app/views/drivers/_form.html.erb
<%= form_with(model: driver, remote: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% driver.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, 'Nombre:' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, 'Apellidos:' %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone, 'Movil:' %>
    <%= form.text_field :phone, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email, 'eMail:' %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :vehicle_id, 'Vehículo:' %>
    <%= form.collection_select(:vehicle_id, Vehicle.all, :id, :load_id, {:prompt => 'Seleccione vehículo...'}, {:class => 'form-control'}) %>
  </div>

  <div class="actions">
    <%= form.submit 'Agregar Vehículo', class: 'btn btn-primary', data:{disable_with: '<i class="fas fa-spinner fa-spin"></i> Guardando Conductor...'}%>
  </div>
<% end %>

app/views/drivers/create.html.erb
<h1>Drivers#create</h1>
<p>Find me in app/views/drivers/create.html.erb</p>

app/views/drivers/create.js.erb
$("#app-modal").modal("hide");
$("#drivers-table").prepend("<%= j render 'drivers/driver_tr', product: @product %>");

app/views/drivers/destroy.html.erb
<h1>Drivers#destroy</h1>
<p>Find me in app/views/drivers/destroy.html.erb</p>

app/views/drivers/edit.html.erb
<h1>Drivers#edit</h1>
<p>Find me in app/views/drivers/edit.html.erb</p>

app/views/drivers/edit.js.erb
$("#app-modal").modal("show");
$('#modal-title').html("Editar Conductor");
$("#modal-body").html("<%= j render 'form', driver: @driver %>");

app/views/drivers/index.html.erb
<div class="row">
  <div class="col-12">
    <h1>Conductores</h1>
    <p>Listado de todos los Conductores registrados en la plataforma</p>
    <%= link_to 'Agregar Conductor', new_driver_path, class: 'btn btn-sm btn-dark mb-2', remote: true %>
    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th scope="col">#id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Apellidos</th>
        <th scope="col">Movil</th>
        <th scope="col">email</th>
        <th scope="col">ID Vehículo / Patente</th>
        <th scope="col">Acciones</th>
      </tr>
      </thead>
      <tbody id="drivers-table">
      <% if @drivers.present?  %>
        <% @drivers.each do |driver| %>
          <%= render "driver_tr", driver: driver %>
        <% end %>
      <% else %>
        <tr>
          <th colspan="4">
            No hay vehiculos registrados.
          </th>
        </tr>
      <%end  %>
      </tbody>
    </table>
    <%= render "partials/modal" %>
  </div>
</div>

app/views/drivers/new.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <h1>Drivers#new</h1>
    <p>Find me in app/views/drivers/new.html.erb</p>
    <%= render 'form', driver: @driver1 %>
  </div>
</div>

app/views/drivers/new.js.erb
$("#app-modal").modal("show");
$('#modal-title').html("Ingresar nuevo Conductor");
$("#modal-body").html("<%= j render 'form', driver: @driver %>");

app/views/drivers/show.html.erb
<h1>Drivers#show</h1>
<p>Find me in app/views/drivers/show.html.erb</p>

app/views/drivers/update.js.erb
$("#app-modal").modal("hide");
$("#driver-<%= @driver.id %>").replaceWith("<%= j render(partial: 'drivers/driver_tr', driver: @driver) %>");