config/routes.rb
Rails.application.routes.draw do
  root to: 'main#home'
  resources :services
  resources :vehicles
  resources :drivers
  resources :routes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :load
  has_many :routes, dependent: :destroy
  belongs_to :driver, optional: true
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  def index
    @vehicles = Vehicle.all.includes(:driver, :load)
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
        format.js
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
        format.js
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def destroy
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:load_id, :driver_id, :capacity, :vehicle_patent)
  end

end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, remote: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% vehicle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :vehicle_patent, 'Patente del vehículo' %>
    <%= form.text_field :vehicle_patent, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :load_id, 'Tipo de carga' %>
    <%= form.collection_select(:load_id, Load.all.order(:type_load), :id, :type_load, {:prompt => 'Seleccione tipo de carga...'}, {:class => 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= form.label :capacity, 'Capacidad total del vehiculo (.Kg)' %>
    <%= form.number_field :capacity, class: 'form-control', step: :any %>
  </div>

  <div class="actions">
    <%= form.submit 'Agregar Vehículo', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/vehicles/_vehicle_tr.html.erb
<% vehicle = vehicle.nil? ? @vehicle : vehicle %>
<tr id="vehicle-<%= vehicle.id %>">
  <th scope="row"><%= vehicle.id %></th>
  <td><%= vehicle.vehicle_patent.present? ? vehicle.vehicle_patent : "Vehiculo sin Patente" %></td>
  <td><%= vehicle.load.type_load %></td>
  <td><%= vehicle.driver_id ? "id ❱ #{vehicle.driver_id} / #{vehicle.driver.full_name}"  : "Sin Conductor Asignado" %></td>
  <td><%= vehicle.capacity %></td>
  <td><%= link_to "Editar", edit_vehicle_path(vehicle.id), remote: true %></td>
</tr>

app/views/vehicles/create.html.erb
<h1>Vehicles#create</h1>
<p>Find me in app/views/vehicles/create.html.erb</p>

app/views/vehicles/create.js.erb
$("#app-modal").modal("hide");
$("#vehicle-table").prepend("<%= j render 'vehicle_tr', vehicle: @vehicle %>");

app/views/vehicles/destroy.html.erb
<h1>Vehicles#destroy</h1>
<p>Find me in app/views/vehicles/destroy.html.erb</p>

app/views/vehicles/edit.html.erb
<h1>Vehicles#edit</h1>
<p>Find me in app/views/vehicles/edit.html.erb</p>

app/views/vehicles/edit.js.erb
$("#app-modal").modal("show");
$('#modal-title').html("Editar Vehículo");
$("#modal-body").html("<%= j render 'vehicles/form', vehicle: @vehicle %>");

app/views/vehicles/index.html.erb
<div class="row ">
  <div class="col-12">
    <h1>Flota de vehiculos</h1>
    <p>Listado de todos los vehiculos disponibles de la organización.</p>
    <%= link_to 'Agregar Vehiculo', new_vehicle_path, class: 'btn btn-sm btn-dark mb-2', remote: true %>
    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th scope="col">#id</th>
        <th scope="col">Patente</th>
        <th scope="col">Tipo de carga</th>
        <th scope="col">Conductor</th>
        <th scope="col">Capacidad Máxima</th>
        <th scope="col">Acciones</th>
      </tr>
      </thead>
      <tbody id="vehicle-table">
      <% if @vehicles.present?  %>
        <% @vehicles.each do |vehicle| %>
          <%= render "vehicle_tr", vehicle: vehicle %>

        <% end %>
        <% else %>
        <tr>
          <th colspan="4">
            No hay vehiculos registrados.
          </th>
        </tr>
      <%end  %>
      </tbody>
    </table>
    <%= render "partials/modal" %>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <h1>Vehicles#new</h1>
    <p>Find me in app/views/vehicles/new.html.erb</p>
    <%= render 'form', vehicle: @vehicle %>
  </div>
</div>

app/views/vehicles/new.js.erb
$("#app-modal").modal("show");
$('#modal-title').html("Ingresar nuevo Vehículo");
$("#modal-body").html("<%= j render 'form', vehicle: @vehicle %>");

app/views/vehicles/show.html.erb
<h1>Vehicles#show</h1>
<p>Find me in app/views/vehicles/show.html.erb</p>

app/views/vehicles/update.html.erb
<h1>Vehicles#update</h1>
<p>Find me in app/views/vehicles/update.html.erb</p>

app/views/vehicles/update.js.erb
$("#app-modal").modal("hide");
$("#vehicle-<%= @vehicle.id %>").replaceWith("<%= j render(partial: 'vehicle_tr', vehicle: @vehicle) %>");